//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupCategoryType
    {
        public int GroupCategoryTypeId { get; set; }
        public string GroupCategoryTypeName { get; set; }
        public System.TimeSpan GroupCategoryTypeStartTime { get; set; }
        public System.TimeSpan GroupCategoryTypeEndTime { get; set; }
    }
}
