//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public int GroupId { get; set; }
        public string StudentName { get; set; }
        public string StudentSurname { get; set; }
        public System.DateTime StudentBirthDate { get; set; }
        public string StudentEmail { get; set; }
        public string StudentPhone { get; set; }
        public Nullable<System.DateTime> StudentRegistrationDate { get; set; }
        public string StudentPhoto { get; set; }
        public string StudentBio { get; set; }
    }
}
